### ISSUE TITLE
example.js does not work.

### ISSUE THREAD

**Issue by raymerjacque** [skzhengkai/vyro.ai-imagine#2]
imagine.js:11
    'style-id': Style[style][0] || '30'
                            ^

TypeError: Cannot read properties of undefined (reading '0')

**Comment by BackendAdam** [comment]
i think that occurs when you put a style that either isn't in constants.js, or don't put a style at all. ill get this fixed later today, thanks for the report!

**Comment by BackendAdam** [comment]
on second thought I'll close it once I fix it

**Comment by BackendAdam** [comment]
this should be fixed now, thanks
