### ISSUE TITLE
406 Client Error:

### ISSUE THREAD

**Issue by raymerjacque** [skzhengkai/vyro.ai-imagine#3]
406 Client Error: Not Acceptable for url: https://api.vyro.ai/v1/imagine/web/generations
An error occurred while generating the image: cannot identify image file <_io.BytesIO object at 0x000001EA5B8982C0>

**Comment by BackendAdam** [comment]
can you please show me the code you're using? the api doesn't seem to have changed.

**Comment by raymerjacque** [comment]
i found the problem. the bearer token had changed. i updated the token and its working again :)

I converted your scripts into python and got it working... but i am not a very good coder... so its been quite the task.  I'm going to create a Github, and then ill send you the url. perhaps you can fork it, it could be useful.... and then you can see what i did.

**Comment by raymerjacque** [comment]
I found the problem, the stupid bearer token had changed, i was not aware it changes... updated the token and all is working.

btw, I ported your project into Python. and i made a really nice GUI to generate images. you can check it out here :

https://github.com/raymerjacque/vyro-imagine-ai

**Comment by BackendAdam** [comment]
i should probably note in the README.md file that bearer's expire after 24h. i'll be working to make it so that in the future you won't need to put in a bearer at all. i'm glad you found the issue, and it's cool that you made a python version of my project!
